[tool.poetry]
name = "minst-mlops"
version = "0.1.0"
description = ""
authors = ["mohamed-14 <amrsalem7711@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scikit-learn = "^1.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
